rule all:
	input:
		"summaries/summary_June_11_2019.svg"

rule addMetaData:
	input:
		"testFiles/example.json"
	output:
		"tempOutput.json"
	shell:
		"python3 -c 'import metaDataMiner as mdm; mdm.processFile(\"{input}\",\"{output}\",True,\"172.17.0.3\")'"

rule filterBenign:
	input:
		"tempOutput.json"
	output:
		"testFiles/test.json"
	shell:
		"""
		python3 -c 'import dataFilter as df; df.filterBenign(\"{input}\",\"{output}\")',
		rm tempOutput.json
		"""

rule makeReport:
	input:
		original="testFiles/example.json",
		results="testFiles/test.json"
	output:
		"testFiles/test.html"
	shell:
		"python3 -c 'import report as rp; rp.createReport(\"{input.original}\",\"{input.results}\",\"{output}\")'"

rule getSummary:
	input:
		bait = "testFiles/test.html",
		results ="testFiles/test.json",
		original ="testFiles/example.json"
	output:
		"summaries/summary_June_11_2019.svg"
	shell:
		"python3 -c 'import summary as sm; sm.getSummary(\"{input.results}\",\"{output}\",\"{input.original}\")' && cat summaries/summary_June_11_2019.svg"
