rule all:
	input:
		"test.json"

#rule viewWorkflow:


rule addMetaData:
	input:
		"example.json"
	output:
		"test.json"
	shell:
		"python3 -c 'import metaDataMiner as mdm; mdm.processFile(\"{input}\",\"{output}\")'"
